---
abstract: 'A custom trait to include roles in serialization'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Moose: '0'
  MooseX::Role::Parameterized: '0'
  MooseX::Storage: '0'
  Test::Deep: '0'
  Test::More: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Storage-Traits-WithRoles
provides:
  MooseX::Storage::Base::SerializedClass:
    file: lib/MooseX/Storage/Base/SerializedClass.pm
    version: v0.2.0
  MooseX::Storage::Engine::Trait::WithRoles:
    file: lib/MooseX/Storage/Engine/Trait/WithRoles.pm
    version: v0.2.0
  MooseX::Storage::Traits::WithRoles:
    file: lib/MooseX/Storage/Traits/WithRoles.pm
    version: v0.2.0
requires:
  Class::Load: '0'
  Exporter: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  MooseX::Storage::Basic: '0'
  namespace::autoclean: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/yanick/MooseX-Storage-Traits-WithRoles/issues
  homepage: https://github.com/yanick/MooseX-Storage-Traits-WithRoles
  repository: https://github.com/yanick/MooseX-Storage-Traits-WithRoles.git
version: 0.2.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
